// RUN DATA
export const REQUEST_GET_RUNS = "REQUEST_GET_RUNS";
export const RECEIVE_GET_RUNS = "RECEIVE_GET_RUNS";
export const REQUEST_POST_RUN = "REQUEST_POST_RUN";
export const RECEIVE_POST_RUN = "RECEIVE_POST_RUN";
export const REQUEST_DELETE_RUN = "REQUEST_DELETE_RUN";
export const RECEIVE_DELETE_RUN = "RECEIVE_DELETE_RUN";

// UI
export const SET_START_DATE = "SET_START_DATE";
export const SET_END_DATE = "SET_END_DATE";
export const TOGGLE_ADDRUN_MODAL = "TOGGLE_ADDRUN_MODAL";
export const TOGGLE_DAY_MODAL = "TOGGLE_DAY_MODAL";
export const SET_DAY_MODAL_DETAILS = "SET_DAY_MODAL_DETAILS";

// BROWSER LOCATION
export const REQUEST_BROWSER_COORDS = "REQUEST_BROWSER_COORDS";
export const RECEIVE_BROWSER_COORDS = "RECEIVE_BROWSER_COORDS";
export const SET_BROWSER_COORDS = "SET_BROWSER_COORDS";
export const SET_BROWSER_LOCATION = "SET_BROWSER_LOCATION";

// LAT LONG
export const REQUEST_LOCATION = "REQUEST_LOCATION";
export const RECEIVE_LOCATION = "RECEIVE_LOCATION";

// WEATHER
export const REQUEST_WEATHER = "REQUEST_WEATHER";
export const RECEIVE_WEATHER = "RECEIVE_WEATHER";
export const STORE_WEATHER = "STORE_WEATHER";

//TEMP
export const SET_USER = "SET_USER";
export const SET_RUNS = "SET_RUNS";
